version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
      - "script.inline=true"
      - "script.indexed=true"
      - "script.engine.groovy.inline.aggs=true"
      - "script.engine.groovy.inline.search=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - elasdataa1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.0
    environment:
      - cluster.name=docker-cluster
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "xpack.security.enabled=false"
      - "script.inline=true"
      - "script.indexed=true"
      - "script.engine.groovy.inline.aggs=true"
      - "script.engine.groovy.inline.search=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - elasdataa2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  elasdataa1:
    driver: local
  elasdataa2:
    driver: local

networks:
  esnet:
    driver: bridge
